services:
  app:
    image: ${DOCKER_IMAGE}
    restart: always
    expose:
      - "80"

  caddy:
    image: caddy:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

  watchtower:
    image: containrrr/watchtower:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/.docker/config.json:/config.json
    command: --interval 60 --cleanup
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:
